python/sglang/srt/layers/moe/topk.py, sgl-kernel/benchmark/bench_deepseekv3_fused_gate.py, sgl-kernel/csrc/moe/deepseek_fused_gate.cu, sgl-kernel/csrc/torch_extension.cc, sgl-kernel/include/sgl_kernel_ops.h, sgl-kernel/python/sgl_kernel/__init__.py, sgl-kernel/python/sgl_kernel/moe.py, sgl-kernel/setup.py, sgl-kernel/tests/test_deepseek_fused_gate.py
Note: The sigmoid gate CUDA kernel implementation was contributed by another developer, and the MR has not yet been merged into the SGLang upstream. Ref: https://github.com/sgl-project/sglang/pull/3191
I integrated the sigmoid gate CUDA kernel into the current code and rebased it to the latest, and conducted a comprehensive performance evaluation, and confirmed that it provides a performance gain.
=> Feat: Sigmoid Gate Cuda Kernel Integration

python/sglang/srt/layers/moe/ep_moe/kernels.py, python/sglang/srt/server_args.py
=> Improve EP performance

python/sglang/srt/connector/__init__.py, python/sglang/srt/connector/base_connector.py, python/sglang/srt/connector/file.py, python/sglang/srt/connector/hpkv.py, python/sglang/srt/connector/redis.py, python/sglang/srt/connector/serde/__init__.py, python/sglang/srt/connector/serde/safe_serde.py, python/sglang/srt/model_loader/loader.py, python/sglang/test/test_connector.py
=> feat(remote_model): support hpkv

python/sglang/srt/layers/moe/fused_moe_triton/configs/E=264,N=256,device_name=NVIDIA_H20-3e,dtype=fp8_w8a8,block_shape=[128, 128].json
=> feat(fused_moe): H20 tune configs

python/sglang/srt/observability.py, python/sglang/srt/openai_api/adapter.py
=> feat: add trace and metrics via opentelemetry

python/sglang/srt/observability.py
=> feat: update trace context

python/sglang/srt/connector/__init__.py, python/sglang/srt/connector/base_connector.py, python/sglang/srt/connector/file.py, python/sglang/srt/connector/hpkv.py, python/sglang/srt/connector/redis.py, python/sglang/srt/connector/serde/__init__.py, python/sglang/srt/connector/serde/safe_serde.py, python/sglang/srt/model_loader/loader.py, python/sglang/test/test_connector.py
=> Gdkv release 0.0.2

examples/runtime/engine/save_remote_state.py, python/sglang/srt/hf_transformers_utils.py, python/sglang/srt/managers/scheduler.py, python/sglang/srt/model_loader/loader.py, python/sglang/srt/models/deepseek_nextn.py
=> fix(nextn): support nextn mtp

python/sglang/srt/mem_cache/eic_hiradix_cache.py, python/sglang/srt/mem_cache/eic_memory_pool.py
=> fix write back policy

python/sglang/srt/disaggregation/nixl/conn.py
该 PR cherry-pick 自 https://github.com/sgl-project/sglang/pull/5681 
根据我们的测试，这次修改使得 PD 分离的性能提升 36%（280 -> 180）。
=> Cherrypick [PD] NIXL backend Prefill TP & Decode TP+DP (#5681)

benchmark/config/deepep_tuned_H20_4rnic.json, docker/Dockerfile.deepep, python/sglang/srt/disaggregation/mini_lb.py, python/sglang/srt/managers/data_parallel_controller.py, python/sglang/srt/managers/tokenizer_manager.py
=> Tune deepep for H20 && fix poll requests

docker/Dockerfile.deepep
=> update deepep ,support low lantency kernel use nvlink

python/build_scm.sh, sgl-kernel/build_scm.sh
=> build(scm): special ep_main branch wheel name

python/sglang/srt/disaggregation/prefill.py, python/sglang/srt/managers/schedule_batch.py
=> avoid to send the remote prefill request to detokenizer

docker/Dockerfile.deepep
=> fix(ci): fix pip install error in icm

docker/Dockerfile.byted, python/sglang/srt/layers/quantization/fp8.py
=> [FIX] Cutlass moe dep install  fix

docker/Dockerfile.byted
=> feat: group gemm install

python/sglang/srt/disaggregation/decode.py, python/sglang/srt/disaggregation/decode_schedule_batch_mixin.py, python/sglang/srt/disaggregation/prefill.py, python/sglang/srt/disaggregation/utils.py, python/sglang/srt/layers/attention/flashattention_backend.py, python/sglang/srt/managers/schedule_batch.py, python/sglang/srt/managers/scheduler.py, python/sglang/srt/model_executor/cuda_graph_runner.py, python/sglang/srt/speculative/eagle_utils.py, python/sglang/srt/speculative/eagle_worker.py
=> Perormance: Enable cuda graph for dp idle batch

sgl-kernel/csrc/quantization/cutlass_w8a8/moe/grouped_mm_c3x.cu
=> [OPT] Qwen3-235B-MOE cutlass tuning

python/sglang/srt/managers/expert_location_dispatch.py, python/sglang/srt/managers/schedule_batch.py
Resolve hardcode issue for testing.
=> fix num_gpu derivation

docker/Dockerfile.byted
add BASE_IMAGE arg to Dockerfile.byted
=> feat(ci): add BASE_IMAGE arg

docker/Dockerfile, docker/Dockerfile.byted
=> feat(ci): using cached nvidia image in iaas-gpu

docker/Dockerfile.byted
=> fix: apt source url

python/sglang/srt/layers/attention/tbo_backend.py, python/sglang/srt/model_executor/cuda_graph_runner.py, python/sglang/srt/model_executor/forward_batch_info.py, python/sglang/srt/model_executor/model_runner.py, python/sglang/srt/operations_strategy.py, python/sglang/srt/two_batch_overlap.py
=> feat: support compatibility between MTP and two-batch-overlap

docker/Dockerfile.byted
=> fp8 version flashmla

python/sglang/srt/layers/moe/cutlass_moe.py
=> [FIX]Solve first launch mismatch

python/sglang/srt/layers/moe/ep_moe/token_dispatcher.py
=> disable mnnvl

python/sglang/srt/two_batch_overlap.py
=> remove log

docker/Dockerfile.byted
=> Update Dockerfile.byted to adapt Dockerfile apt change

python/sglang/srt/layers/quantization/fp8.py, python/sglang/srt/layers/quantization/fp8_kernel.py, sgl-kernel/csrc/quantization/cutlass/cutlass_w8a8/moe/moe_data.cu
之前Qwen3-Moe 打开优化选项 tpot会劣化，修复该问题，同时保持ttft的优化效果 2700ms ->2200ms
=> [FIX] Cutlass moe Tpot performance fix  

docker/Dockerfile.byted
=> fix:install pris sdk

python/sglang/srt/layers/moe/cutlass_moe.py, python/sglang/srt/layers/moe/topk.py, python/sglang/srt/layers/quantization/fp8.py
* add switch for activation static scale
* add fast topk_weight_sum compute
=> [Feat]: add fast topk_weight compute for routing and add switch for static scale

python/sglang/srt/models/deepseek_v2.py
=> Fix: Add None check for quant_config in DeepSeek models.

sgl-kernel/CMakeLists.txt
=> fix: resolve conflicts during upstream rebase

python/sglang/srt/layers/moe/topk.py
=> fix topk error in qwen3 moe model after rebase ep_main

docker/Dockerfile.byted
=> update the description of dockerfile.byted

docker/Dockerfile.byted
=> sglang router docker

python/sglang/srt/model_loader/loader.py
=> feat(quant): support quant for gdkv

python/sglang/srt/layers/quantization/fp8_utils.py, python/sglang/srt/utils.py, sgl-kernel/benchmark/bench_fp8_blockwise_gemm.py, sgl-kernel/csrc/cutlass_extensions/epilogue/collective/default_epilogue.hpp, sgl-kernel/csrc/cutlass_extensions/epilogue/thread/conversion_op.h, sgl-kernel/csrc/cutlass_extensions/sm89/collective/collective_builder.hpp, sgl-kernel/csrc/cutlass_extensions/sm89/collective/collective_mma.hpp, sgl-kernel/csrc/cutlass_extensions/sm89/collective/sm80_mma_multistage_blockwise_scaling.hpp, sgl-kernel/csrc/cutlass_extensions/sm89/collective/sm80_mma_multistage_blockwise_scaling_overlap.hpp, sgl-kernel/csrc/cutlass_extensions/sm89/dispatch_policy_extention.hpp, sgl-kernel/csrc/cutlass_extensions/sm89/kernel/gemm_universal.hpp, sgl-kernel/csrc/cutlass_extensions/sm89/kernel/sm70_gemm_blockscaled_accum.hpp, sgl-kernel/csrc/gemm/fp8_blockwise_gemm_kernel.cu
=> Support block-wise gemm for dense model(Qwen3-32B-Fp8) in L20 

examples/monitoring/grafana/dashboards/json/sglang-dashboard.json, python/sglang/srt/managers/cache_controller.py, python/sglang/srt/mem_cache/hicache_storage.py, python/sglang/srt/mem_cache/hicache_storage_priskv.py, python/sglang/srt/mem_cache/hiradix_cache.py, python/sglang/srt/mem_cache/memory_pool_host.py, python/sglang/srt/server_args.py
=> storage layer support priskv

python/sglang/srt/managers/mm_utils.py, python/sglang/srt/managers/schedule_batch.py, python/sglang/srt/multimodal/processors/base_processor.py
this code was based on transformers==4.5.1 while sglang 4.9.post3 requires 4.5.3
=> [Revert] Revert VLM Input cache for transformers's version not matched

sgl-kernel/build_scm.sh
=> Update build_scm.sh to update sgl kernel compile env to cuda 12.6

python/sglang/srt/observability.py
=> feat: update apmplus trace span attribute name

python/sglang/srt/managers/mm_utils.py, python/sglang/srt/managers/schedule_batch.py, python/sglang/srt/multimodal/processors/base_processor.py
* modify logic for image input cache to get rid of transformer version's dependency
* add  hashtabel's capacity control
* open this optimization with SGL_CACHE_MM_IMAGE=1
=> [Feat] refactor mm_image cache data logic and add  hashtabel's capacity control

python/sglang/srt/layers/attention/hybrid_attn_backend.py, python/sglang/srt/managers/schedule_batch.py, python/sglang/srt/model_executor/model_runner.py, python/sglang/srt/models/deepseek_v2.py, python/sglang/srt/server_args.py, sgl-kernel/csrc/moe/moe_fused_gate.cu
=> qwen235B performance enhancement

docker/Dockerfile.byted
INFO: pip is looking at multiple versions of flashinfer-python to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install sglang and sglang[srt]==0.4.9.post3 because these package versions have conflicting dependencies.
The conflict is caused by:
sglang[srt] 0.4.9.post3 depends on torch==2.7.1; extra == "srt"
flashinfer-python 0.2.7.post1 depends on torch
flashinfer-python 0.2.7.post1 depends on torch==2.8.*
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
=> fix: first use volces.com to install flashinfer_python to fix confilct

docker/Dockerfile.byted
=> Fix flashinfer torch conflict

python/sglang/srt/managers/eic_cache_controller.py, python/sglang/srt/managers/scheduler.py, python/sglang/srt/mem_cache/eic_chunk_cache.py
EIC chunk cache修正；适配大EP PD分离场景，在多轮会话时使decode实例也会set EIC kvcache
=> fix eic chunk cache

python/sglang/srt/eplb/eplb_manager.py
=> fix export eplb json

docker/Dockerfile
=> use byted.org tos to cache clangd&cmake

docker/Dockerfile
use bytedance-iaas code to build sglang when build base image
=> [dockerfile]use bytedance-iaas code to build sglang

python/sglang/srt/managers/eic_cache_controller.py, python/sglang/srt/mem_cache/eic_memory_pool.py
=> fix eic partial get fail

python/sglang/srt/mem_cache/eic_memory_pool.py
=> reduce eic batch exist key number

python/sglang/srt/mem_cache/eic_hiradix_cache.py, python/sglang/srt/mem_cache/eic_memory_pool.py
use namespace and batch exist for optimize latency and hit rate
=> add eic exist and namespace optimize

python/sglang/srt/layers/moe/cutlass_w4a8_moe.py, python/sglang/srt/layers/moe/ep_moe/layer.py, python/sglang/srt/layers/moe/fused_moe_triton/layer.py, python/sglang/srt/layers/quantization/w4afp8.py, python/sglang/srt/models/deepseek_v2.py, sgl-kernel/csrc/moe/cutlass_moe/w4a8/w4a8_get_group_starts.cuh, sgl-kernel/csrc/moe/cutlass_moe/w4a8/w4a8_grouped_mm_c3x.cu, sgl-kernel/csrc/moe/cutlass_moe/w4a8/w4a8_grouped_mm_c3x.cuh
=> support w4a8 TP

python/sglang/srt/managers/eic_cache_controller.py, python/sglang/srt/managers/schedule_policy.py, python/sglang/srt/managers/scheduler_metrics_mixin.py, python/sglang/srt/mem_cache/eic_hiradix_cache.py, python/sglang/srt/mem_cache/eic_memory_pool.py
=> add partial fail exist and backgroud check

python/sglang/srt/managers/schedule_batch.py, python/sglang/srt/managers/scheduler.py, python/sglang/srt/managers/scheduler_metrics_mixin.py, python/sglang/srt/managers/scheduler_output_processor_mixin.py, python/sglang/srt/mem_cache/eic_hiradix_cache.py, python/sglang/srt/mem_cache/hiradix_cache.py, python/sglang/srt/metrics/collector.py
=> feat(metrics): add scheduler and hiradix cache metrics

python/sglang/srt/managers/scheduler.py
=> fix(metrics): fix HiRadixCache init when metric is off

sgl-router/build.sh, sgl-router/build_scm.sh
=> feat: add router ci

docker/Dockerfile.byted
=> feat: add self-build sglang router install in sglang image

sgl-router/build.sh
=> [sgl-router] use local rustup install to make router build faster

.gitignore, python/sglang/srt/entrypoints/http_server.py, python/sglang/srt/managers/eic_cache_controller.py, python/sglang/srt/managers/io_struct.py, python/sglang/srt/managers/schedule_policy.py, python/sglang/srt/managers/scheduler.py, python/sglang/srt/managers/scheduler_metrics_mixin.py, python/sglang/srt/managers/scheduler_output_processor_mixin.py, python/sglang/srt/managers/tokenizer_communicator_mixin.py, python/sglang/srt/managers/tokenizer_manager.py, python/sglang/srt/mem_cache/eic_chunk_cache.py, python/sglang/srt/mem_cache/eic_hiradix_cache.py, python/sglang/srt/mem_cache/eic_memory_pool.py, python/sglang/srt/mem_cache/radix_cache.py, python/sglang/srt/metrics/collector.py, python/sglang/srt/server_args.py, python/sglang/srt/speculative/eagle_utils.py
Co-authored-by: mashisong <mashisong@bytedance.com>
fix eic chunk cache (#224) and 0814 cherry-pick
Co-authored-by: mashisong <mashisong@bytedance.com>
fix eic partial get fail
reduce eic batch exist key number
add eic exist and namespace optimize
fix eic cache hit rate
add partial fail exist and backgroud check
=> add eic for speech

docker/Dockerfile.byted, python/sglang/srt/managers/mm_utils.py, python/sglang/srt/managers/schedule_batch.py, python/sglang/srt/multimodal/mm_utils.py, python/sglang/srt/multimodal/processors/glm4v.py, python/sglang/srt/multimodal/processors/qwen_vl.py
- **AI Agents**  
Multiple images are often passed as input, but usually only one is new. Caching prevents redundant preprocessing of repeated images.
- **Robotics / Navigation**  
Frequent re-use of similar frames can benefit from fast cache retrieval and IPC-based transmission.
```bash
export SGL_CACHE_MM_IMAGE=1
export SGL_TOKENIZER_CACHED_IMAGE_SIZE_MB=1024 #(max cache 1024MB image data)
```
~~mange cache by using MB_SIZE instead of  image nums~~ (done)
* Works with both qwen2-image-processor and glm4v-image-processor.
* CUDA IPC is automatically applied only in cache mode.
* Designed for scenarios where image reuse is common, improving both speed and efficiency.
python3 test_vlm_perf.py sglang 10 (cua steps)
qwen2.5vl-7B tp2 : 6914.15 ms -> 4998.39ms
GLM4.5V-108B tp4 : 7514.86ms -> …
=> [OPT] : add preprocess optimization for GLM4.5V and qwen2.5vl

python/sglang/srt/connector/__init__.py, python/sglang/srt/connector/hpkv.py, python/sglang/srt/connector/pris.py, python/sglang/srt/managers/data_parallel_controller.py, python/sglang/srt/model_loader/loader.py, python/sglang/srt/server_args.py
=> Ep main pris

python/sglang/srt/hf_transformers_utils.py, python/sglang/srt/model_loader/loader.py
=> support kimi & VLM

docker/Dockerfile.byted
=> [dockerfile]feat: add deepgemm cache in image
